- name: MultiPlaybook2
  hosts:  localhost
  become: yes
  tasks:
  - name: Playbook1
    ansible.builtin.debug:
      msg:  "Hello from task1 and playbook1" 

- name: MultiPlaybook1
  hosts:  localhost
  become: yes
  tasks:
  - name: Playbook2
    ansible.builtin.debug:
      msg:  "Hello from task2 and playbook2" 
