- name: install and start niginx
  hosts:  web
  become: yes
  tasks:
  - name: install nigin
    ansible.builtin.dnf:
      name: nginx
      state:  latest
  - name: start niginx
    ansible.builtin.service:
      name: nginx
      state:  started
      enabled:  yes

  