- name: variables
  hosts:  localhost
  vars:
    course: DevOps
    Trainer:  Siva
    Duration: 3.5months
  tasks:
  - name: Print Information
    vars:
      course: Terraform
      Trainer:  Siva
      Duration: 3.5months
    ansible.builtin.debug:
      msg: "Hi, I am learning {{course}} from {{Trainer}} with duration {{Duration}}"
