- name: checking variable preperence
  hosts: localhost
  vars:
    WISHES: Morning from play variable
  vars_files:
  -  vars.yaml
  tasks:
  - name: check prepfernces
    ansible.builtin.debug:
      msg: "Hello, good {{WISHES}}"