- name: variable through prompts
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: please enter your username
    private: false

  - name: PASSWORD
    prompt: please enter your password
    private: true

  tasks:
  - name: print through prompt variables
    ansible.builtin.debug:
      msg: "Hi, {{USERNAME}} and your password is {{PASSWORD}}"
